name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
      id: go
    
    - name: Install golang-migrate CLI
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz -o migrate.linux-amd64.tar.gz
       tar -xzf migrate.linux-amd64.tar.gz
       sudo mv  migrate /usr/bin/migrate
       sudo chmod +x /usr/bin/migrate
       which migrate

    - name: Run migrations
      run: make migrateup
    
    - name: Create env file
      run: |
       echo "DB_DRIVER=postgres" >> app.env
       echo "DB_SOURCE=postgresql://postgres:secret@localhost:5433/simple_bank?sslmode=disable" >> app.env
       echo "SERVER_ADDRESS=0.0.0.0:8080" >> app.env
       echo "TOKEN_SYMMETRIC_KEY=supersecretkey123456789012345678" >> app.env
       echo "ACCESS_TOKEN_DURATION=15m" >> app.env
    
    - name: Test
      run: make test
